# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindiag.ui'
#
# Created: Wed Apr 17 14:36:53 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(921, 550)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 881, 381))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(16, 20, 48, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(19, 60, 48, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 48, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 48, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 36, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(90, 60, 133, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 120, 133, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 150, 133, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.radioButton = QtGui.QRadioButton(self.tab)
        self.radioButton.setGeometry(QtCore.QRect(90, 90, 47, 16))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.tab)
        self.radioButton_2.setGeometry(QtCore.QRect(150, 90, 59, 16))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.prono = QtGui.QComboBox(self.tab)
        self.prono.setGeometry(QtCore.QRect(90, 20, 69, 20))
        self.prono.setObjectName(_fromUtf8("prono"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 180, 36, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(10, 270, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lineEdit_8 = QtGui.QLineEdit(self.tab)
        self.lineEdit_8.setGeometry(QtCore.QRect(90, 180, 133, 20))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 270, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.tableView_2 = QtGui.QTableView(self.tab)
        self.tableView_2.setGeometry(QtCore.QRect(260, 10, 611, 331))
        self.tableView_2.setObjectName(_fromUtf8("tableView_2"))
        self.lineEdit_12 = QtGui.QLineEdit(self.tab)
        self.lineEdit_12.setGeometry(QtCore.QRect(90, 220, 133, 20))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(20, 220, 36, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.radioButton_3 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_3.setGeometry(QtCore.QRect(160, 90, 61, 16))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 200, 113, 20))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 290, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 60, 113, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 54, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 120, 54, 12))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(20, 200, 54, 12))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.radioButton_4 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_4.setGeometry(QtCore.QRect(90, 90, 51, 16))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 54, 12))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.pushButton_4 = QtGui.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 290, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 120, 113, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(90, 160, 113, 20))
        self.lineEdit_7.setText(_fromUtf8(""))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(20, 160, 54, 12))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox = QtGui.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(90, 30, 81, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.tableView_5 = QtGui.QTableView(self.tab_3)
        self.tableView_5.setGeometry(QtCore.QRect(240, 10, 631, 331))
        self.tableView_5.setObjectName(_fromUtf8("tableView_5"))
        self.label_29 = QtGui.QLabel(self.tab_3)
        self.label_29.setGeometry(QtCore.QRect(20, 230, 54, 12))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.lineEdit_21 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_21.setGeometry(QtCore.QRect(90, 230, 113, 20))
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.lineEdit_13 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(90, 260, 133, 20))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.label_31 = QtGui.QLabel(self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(20, 260, 36, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.radioButton_5 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_5.setGeometry(QtCore.QRect(30, 80, 51, 16))
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(80, 50, 113, 20))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.comboBox_2 = QtGui.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 10, 69, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.radioButton_6 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_6.setGeometry(QtCore.QRect(100, 80, 71, 16))
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.pushButton_8 = QtGui.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 110, 75, 23))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.tableView_3 = QtGui.QTableView(self.tab_2)
        self.tableView_3.setGeometry(QtCore.QRect(210, 30, 661, 141))
        self.tableView_3.setObjectName(_fromUtf8("tableView_3"))
        self.tableView_4 = QtGui.QTableView(self.tab_2)
        self.tableView_4.setGeometry(QtCore.QRect(210, 200, 661, 151))
        self.tableView_4.setObjectName(_fromUtf8("tableView_4"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(210, 10, 54, 12))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(210, 180, 54, 12))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 150, 98, 176))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_23 = QtGui.QLabel(self.layoutWidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout.addWidget(self.label_23)
        self.label_24 = QtGui.QLabel(self.layoutWidget)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout.addWidget(self.label_24)
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout.addWidget(self.label_19)
        self.label_21 = QtGui.QLabel(self.layoutWidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout.addWidget(self.label_21)
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout.addWidget(self.label_20)
        self.label_22 = QtGui.QLabel(self.layoutWidget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout.addWidget(self.label_22)
        self.label_25 = QtGui.QLabel(self.layoutWidget)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout.addWidget(self.label_25)
        self.label_26 = QtGui.QLabel(self.layoutWidget)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout.addWidget(self.label_26)
        self.label_27 = QtGui.QLabel(self.layoutWidget)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout.addWidget(self.label_27)
        self.label_28 = QtGui.QLabel(self.layoutWidget)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout.addWidget(self.label_28)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.pushButton_9 = QtGui.QPushButton(self.tab_5)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 120, 75, 23))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(self.tab_5)
        self.pushButton_10.setGeometry(QtCore.QRect(420, 120, 75, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.tableView_6 = QtGui.QTableView(self.tab_5)
        self.tableView_6.setGeometry(QtCore.QRect(70, 10, 341, 341))
        self.tableView_6.setObjectName(_fromUtf8("tableView_6"))
        self.tableView_7 = QtGui.QTableView(self.tab_5)
        self.tableView_7.setGeometry(QtCore.QRect(500, 10, 351, 341))
        self.tableView_7.setObjectName(_fromUtf8("tableView_7"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tableView_8 = QtGui.QTableView(self.tab_6)
        self.tableView_8.setGeometry(QtCore.QRect(170, 10, 601, 331))
        self.tableView_8.setObjectName(_fromUtf8("tableView_8"))
        self.pushButton_11 = QtGui.QPushButton(self.tab_6)
        self.pushButton_11.setGeometry(QtCore.QRect(60, 80, 75, 23))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_13 = QtGui.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(200, 30, 54, 12))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(70, 30, 113, 20))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_10 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(260, 30, 113, 20))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.pushButton_5 = QtGui.QPushButton(self.tab_4)
        self.pushButton_5.setGeometry(QtCore.QRect(390, 30, 75, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(480, 30, 75, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.tableView = QtGui.QTableView(self.tab_4)
        self.tableView.setGeometry(QtCore.QRect(40, 80, 341, 231))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.pushButton_7 = QtGui.QPushButton(self.tab_4)
        self.pushButton_7.setGeometry(QtCore.QRect(400, 160, 75, 23))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.textEdit = QtGui.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(30, 420, 881, 91))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "物品编号", None))
        self.label_2.setText(_translate("Dialog", "物品名称", None))
        self.label_3.setText(_translate("Dialog", "入库类型", None))
        self.label_4.setText(_translate("Dialog", "入库数量", None))
        self.label_5.setText(_translate("Dialog", "记录人", None))
        self.radioButton.setText(_translate("Dialog", "良品", None))
        self.radioButton_2.setText(_translate("Dialog", "不良品", None))
        self.label_12.setText(_translate("Dialog", "备注：", None))
        self.pushButton.setText(_translate("Dialog", "入库", None))
        self.pushButton_2.setText(_translate("Dialog", "取消", None))
        self.label_30.setText(_translate("Dialog", "库位：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "入库记录", None))
        self.radioButton_3.setText(_translate("Dialog", "不良品", None))
        self.pushButton_3.setText(_translate("Dialog", "出库", None))
        self.label_6.setText(_translate("Dialog", "物品编号", None))
        self.label_7.setText(_translate("Dialog", "出库类型", None))
        self.label_8.setText(_translate("Dialog", "出库数量", None))
        self.label_9.setText(_translate("Dialog", "记录人", None))
        self.radioButton_4.setText(_translate("Dialog", "良品", None))
        self.label_10.setText(_translate("Dialog", "物品名称", None))
        self.pushButton_4.setText(_translate("Dialog", "取消", None))
        self.label_11.setText(_translate("Dialog", "领用人", None))
        self.label_29.setText(_translate("Dialog", "备注", None))
        self.label_31.setText(_translate("Dialog", "库位：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "出库记录", None))
        self.radioButton_5.setText(_translate("Dialog", "良品", None))
        self.label_15.setText(_translate("Dialog", "物品编号：", None))
        self.label_16.setText(_translate("Dialog", "物品名称：", None))
        self.radioButton_6.setText(_translate("Dialog", "不良品", None))
        self.pushButton_8.setText(_translate("Dialog", "查询库存", None))
        self.label_17.setText(_translate("Dialog", "入库记录：", None))
        self.label_18.setText(_translate("Dialog", "出库记录：", None))
        self.label_23.setText(_translate("Dialog", "入库总数：", None))
        self.label_24.setText(_translate("Dialog", "0", None))
        self.label_19.setText(_translate("Dialog", "入库存数：", None))
        self.label_21.setText(_translate("Dialog", "0", None))
        self.label_20.setText(_translate("Dialog", "出库总数：", None))
        self.label_22.setText(_translate("Dialog", "0", None))
        self.label_25.setText(_translate("Dialog", "出库数量：", None))
        self.label_26.setText(_translate("Dialog", "0", None))
        self.label_27.setText(_translate("Dialog", "目前库存数量：", None))
        self.label_28.setText(_translate("Dialog", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "查询记录", None))
        self.pushButton_9.setText(_translate("Dialog", "入库汇总", None))
        self.pushButton_10.setText(_translate("Dialog", "出库汇总", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "汇总", None))
        self.pushButton_11.setText(_translate("Dialog", "库存汇总", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "汇总-2", None))
        self.label_13.setText(_translate("Dialog", "物品编号", None))
        self.label_14.setText(_translate("Dialog", "物品名称", None))
        self.pushButton_5.setText(_translate("Dialog", "添加", None))
        self.pushButton_6.setText(_translate("Dialog", "修改", None))
        self.pushButton_7.setText(_translate("Dialog", "删除", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "添加修改物品编号", None))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

