# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created: Wed Apr 10 17:22:11 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(815, 538)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 791, 491))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.addButton = QtGui.QPushButton(self.tab)
        self.addButton.setGeometry(QtCore.QRect(230, 330, 75, 23))
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.cancelButton = QtGui.QPushButton(self.tab)
        self.cancelButton.setGeometry(QtCore.QRect(410, 330, 75, 23))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 90, 661, 191))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.recordname = QtGui.QLineEdit(self.layoutWidget)
        self.recordname.setObjectName(_fromUtf8("recordname"))
        self.gridLayout.addWidget(self.recordname, 2, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.productname = QtGui.QLineEdit(self.layoutWidget)
        self.productname.setObjectName(_fromUtf8("productname"))
        self.gridLayout.addWidget(self.productname, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 3, 1, 1)
        self.productqty = QtGui.QLineEdit(self.layoutWidget)
        self.productqty.setObjectName(_fromUtf8("productqty"))
        self.gridLayout.addWidget(self.productqty, 1, 4, 1, 1)
        self.outname = QtGui.QLineEdit(self.layoutWidget)
        self.outname.setObjectName(_fromUtf8("outname"))
        self.gridLayout.addWidget(self.outname, 2, 2, 1, 1)
        self.in_out = QtGui.QComboBox(self.layoutWidget)
        self.in_out.setObjectName(_fromUtf8("in_out"))
        self.in_out.addItem(_fromUtf8(""))
        self.in_out.addItem(_fromUtf8(""))
        self.in_out.addItem(_fromUtf8(""))
        self.in_out.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.in_out, 1, 2, 1, 1)
        self.productno = QtGui.QComboBox(self.layoutWidget)
        self.productno.setObjectName(_fromUtf8("productno"))
        self.gridLayout.addWidget(self.productno, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 100, 661, 191))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.proname = QtGui.QLineEdit(self.layoutWidget1)
        self.proname.setObjectName(_fromUtf8("proname"))
        self.gridLayout_2.addWidget(self.proname, 0, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.prono = QtGui.QComboBox(self.layoutWidget1)
        self.prono.setObjectName(_fromUtf8("prono"))
        self.gridLayout_2.addWidget(self.prono, 0, 2, 1, 1)
        self.tableView = QtGui.QTableView(self.layoutWidget1)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout_2.addWidget(self.tableView, 1, 0, 1, 6)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 350, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 350, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.productno)
        MainWindow.setTabOrder(self.productno, self.productname)
        MainWindow.setTabOrder(self.productname, self.in_out)
        MainWindow.setTabOrder(self.in_out, self.productqty)
        MainWindow.setTabOrder(self.productqty, self.outname)
        MainWindow.setTabOrder(self.outname, self.recordname)
        MainWindow.setTabOrder(self.recordname, self.addButton)
        MainWindow.setTabOrder(self.addButton, self.cancelButton)
        MainWindow.setTabOrder(self.cancelButton, self.prono)
        MainWindow.setTabOrder(self.prono, self.proname)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.addButton.setText(_translate("MainWindow", "添加", None))
        self.cancelButton.setText(_translate("MainWindow", "取消", None))
        self.label_11.setText(_translate("MainWindow", "领用人:", None))
        self.label_10.setText(_translate("MainWindow", "记录人：", None))
        self.label_7.setText(_translate("MainWindow", "选项:", None))
        self.label_4.setText(_translate("MainWindow", "物品名称:", None))
        self.label_3.setText(_translate("MainWindow", "物品编号:", None))
        self.label_8.setText(_translate("MainWindow", "数量:", None))
        self.in_out.setItemText(0, _translate("MainWindow", "良品入库", None))
        self.in_out.setItemText(1, _translate("MainWindow", "不良品入库", None))
        self.in_out.setItemText(2, _translate("MainWindow", "良品出库", None))
        self.in_out.setItemText(3, _translate("MainWindow", "不良品出库", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "添加记录", None))
        self.label_6.setText(_translate("MainWindow", "物品编号:", None))
        self.label_5.setText(_translate("MainWindow", "物品名称:", None))
        self.pushButton_3.setText(_translate("MainWindow", "查询", None))
        self.pushButton_4.setText(_translate("MainWindow", "取消", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "查询记录", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "统计", None))
        self.actionAbout.setText(_translate("MainWindow", "&About", None))
        self.actionHelp.setText(_translate("MainWindow", "&Help         &F1", None))
        self.action_Open.setText(_translate("MainWindow", "&Open", None))
        self.action_Close.setText(_translate("MainWindow", "&Close", None))

